support trusty and xenial as osquery repository allows, xenial seems …
kbrebanov/ansible-osquery pull request #1
Opened 2016-10-17 00:26 UTC by juju4

…to require apt-transport-https

2016-10-17 16:00 UTC, kbrebanov requested changes

2016-10-17 16:00 UTC, kbrebanov commented on tasks/Ubuntu.yml
> -  become: yes
Why are you removing the 'become' directive?

2016-10-17 16:00 UTC, kbrebanov commented on tasks/Ubuntu.yml
> -  become: yes
Why are you removing the 'become' directive?

2016-10-17 16:00 UTC, kbrebanov commented on tasks/Ubuntu.yml
> -  become: yes
Why are you removing the 'become' directive?

2016-10-17 16:00 UTC, kbrebanov commented on tasks/Ubuntu.yml
> +  when: ansible_distribution_release == 'xenial'
No need to have a conditional checking if it's Xenial as it's ok to also ensure it's installed on Trusty.

2016-10-17 16:00 UTC, kbrebanov commented on tasks/Ubuntu.yml
> +    repo: 'deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/{{ ansible_distribution_release }} {{ ansible_distribution_release }} main'
I would recommend using the 'lower' filter.

`ansible_distribution_release|lower`

2016-10-17 16:00 UTC, kbrebanov commented on tasks/Ubuntu.yml
> +
Can you remove the trailing newline?

2016-10-17 16:00 UTC, kbrebanov commented on tasks/main.yml
> +
Can you remove the trailing newline?

2016-10-17 23:42 UTC, kbrebanov commented on tasks/main.yml
> +
Or better yet, remove the file from the commit since nothing really needs to be changed in it.

2016-10-18 15:58 UTC, kbrebanov approved these changes

2016-10-18 15:58 UTC, merged

2016-10-19 16:48 UTC, juju4 commented
Thanks Kevin!